spring:
  application:
    name: auth-service

  profiles:
    active: dev

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWK_SET_URI}

server:
  port: 8090

springdoc:
  swagger-ui:
    title: CINEMA API

    description: "Authentication service is a microservice which a part of cinema system and responsible for:\n
                - Login \n
                - Logout \n
                - Refresh access token \n"