spring:
  application:
    name: notification-service

  profiles:
    active: dev

server:
  port: 8094

rabbitmq:
  exchange:
    user: user-exchange
  queue:
    email-verification: email-verification-queue
  routing-key:
    email-verification: user.email-verification