spring:
  application:
    name: notification-service

  profiles:
    active: dev

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: 5672
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

server:
  port: 8094

rabbitmq:
  user:
    email-verification:
      exchange: user.email.exchange
      queue: email-verification-queue
      routing-key: user.email-verification

email:
  source-address: ${EMAIL_SOURCE_ADDRESS}
  verification-url: ${EMAIL_VERIFICATION_URL}

springdoc:
  swagger-ui:
    title: CINEMA API

    description: "Notification service is a microservice which a part of cinema system and responsible for sending notification:\n
                - Email verification notification\n"