spring:
  application:
    name: notification-service

  profiles:
    active: dev

server:
  port: 8094

rabbitmq:
  user:
    email-verification:
      exchange: user.email.exchange
      queue: email-verification-queue
      routing-key: user.email-verification

email:
  source-address: ${EMAIL_SOURCE_ADDRESS}
  verification-url: ${EMAIL_VERIFICATION_URL}

springdoc:
  swagger-ui:
    title: CINEMA API

    description: "Notification service is a microservice which a part of cinema system and responsible for sending notification:\n
                - Email verification notification\n"