spring:
  application:
    name: cinema-service
  profiles:
    active: dev

server:
  port: 8092

springdoc:
  swagger-ui:
    title: CINEMA API

    description: "Cinema service is a microservice which a part of cinema system and responsible for:\n
                - Cinemas management \n
                - Cinema rooms management \n
                - Room seats management \n
                - Movies management \n
                - Genres management \n
                - Showtimes management\n
                - Orders management\n"