spring:
  application:
    name: payment-service
  profiles:
    active: dev

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWK_SET_URI}

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: 5672
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

jwt:
  auth:
    converter:
      principle-attribute: ${PRINCIPLE_ATTRIBUTE}

stripe:
  secret-key: ${STRIPE_SECRET_KEY}
  webhook-secret: ${STRIPE_WEBHOOK_SECRET}
  payment:
    configuration: ${STRIPE_PAYMENT_CONFIG}
    session-expiration: ${STRIPE_SESSION_EXPIRATION}
    success-url: ${STRIPE_SUCCESS_URL}
    failure-url: ${STRIPE_FAILURE_URL}


cinema-service:
  url: ${CINEMA_SERVICE_URL}

server:
  port: 8095

rabbitmq:
  order:
   payment:
      exchange: payment.confirm.exchange
      routing-key: payment.confirm

springdoc:
  swagger-ui:
    title: CINEMA API

    description: "Payment service is a microservice which a part of cinema system and responsible for payments:\n
                - pay for order\n
                - refund payment for order\n"