spring:
  application:
    name: payment-service
  profiles:
    active: dev

server:
  port: 8095


rabbitmq:
  order:
   payment:
      exchange: payment.confirm.exchange
      routing-key: payment.confirm