eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  config:
    import: file:.env[.properties]

  jpa:
    show-sql: true

logging:
  level:
    com.project.mediaservice: debug