spring:
  application:
    name: media-service
  profiles:
    active: dev

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: media_service

  flyway:
    schemas: media_service
    locations: db/migration/base

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWK_SET_URI}

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 10KB
      max-file-size: 20MB
      max-request-size: 50MB

jwt:
  auth:
    converter:
      principle-attribute: ${PRINCIPLE_ATTRIBUTE}

server:
  port: 8093

aws:
  s3:
    access-key: ${AWS_S3_ACCESS_KEY}
    secret-key: ${AWS_S3_SECRET_KEY}
    region: ${AWS_S3_REGION}
    bucket: ${AWS_S3_BUCKET}
    #minutes
    link-expiration: ${AWS_S3_LINK_EXPIRATION}

springdoc:
  swagger-ui:
    title: CINEMA API

    description: "Media service is a microservice which a part of cinema system and responsible for file management:\n
                - Save file \n
                - Get file \n
                - Delete file \n"