spring:
  application:
    name: media-service
  profiles:
    active: dev

server:
  port: 8093

aws:
  s3:
    access-key: ${AWS_S3_ACCESS_KEY}
    secret-key: ${AWS_S3_SECRET_KEY}
    region: ${AWS_S3_REGION}
    bucket: ${AWS_S3_BUCKET}
    #minutes
    link-expiration: ${AWS_S3_LINK_EXPIRATION}