spring:
  application:
    name: user-service
  profiles:
    active: dev

server:
  port: 8091

rabbitmq:
  exchange:
    user: user.exchange
  routing-key:
    email-verification: user.email-verification

#minutes
email:
  retry-interval-time: ${RETRY_INTERVAL_TIME}