spring:
  application:
    name: user-service
  profiles:
    active: dev

server:
  port: 8091

rabbitmq:
  user:
    email-verification:
      exchange: user.email.exchange
      routing-key: user.email-verification

#minutes
email:
  retry-interval-time: ${RETRY_INTERVAL_TIME}


springdoc:
  swagger-ui:
    title: CINEMA API

    description: "User service is a microservice which a part of cinema system and responsible for users:\n
                - Registration\n
                - Email verification\n"