spring:
  application:
    name: user-service
  profiles:
    active: dev

server:
  port: 8091

rabbitmq:
  user:
    email-verification:
      exchange: user.email.exchange
      routing-key: user.email-verification

#minutes
email:
  retry-interval-time: ${RETRY_INTERVAL_TIME}