spring:
  application:
    name: user-service
  profiles:
    active: dev

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: users_service

  flyway:
    schemas: users_service
    locations: db/migration/base

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWK_SET_URI}

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: 5672
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

keycloak:
  admin-username: ${KEYCLOAK_ADMIN_USERNAME}
  admin-password: ${KEYCLOAK_ADMIN_PASSWORD}
  admin-realm: ${KEYCLOAK_ADMIN_REALM}
  admin-resource: ${KEYCLOAK_ADMIN_RESOURCE}
  realm: ${KEYCLOAK_REALM}
  resource: ${KEYCLOAK_RESOURCE}
  auth-server-url: ${KEYCLOAK_AUTH_SERVER_URL}
  credentials:
    secret: ${KEYCLOAK_SECRET}
  base-url: ${KEYCLOAK_BASE_URL}

jwt:
  auth:
    converter:
      principle-attribute: ${PRINCIPLE_ATTRIBUTE}

server:
  port: 8091

rabbitmq:
  user:
    email-verification:
      exchange: user.email.exchange
      routing-key: user.email-verification

#minutes
email:
  retry-interval-time: ${RETRY_INTERVAL_TIME}

springdoc:
  swagger-ui:
    title: CINEMA API

    description: "User service is a microservice which a part of cinema system and responsible for users:\n
                - Registration\n
                - Email verification\n"